package jsplugin

import (
	_ "embed"
	"fmt"
	"reflect"
	"sort"
	"strings"
)

//go:embed tsstatic.d.ts
var tsStatic string

// tsType is one Go contract struct exported to the plugin SDK.
type tsType struct {
	value   any
	name    string
	section string
	// enum, when set, is a string union declared just before this type.
	enum *tsEnum
}

type tsEnum struct {
	name   string
	values []string
}

// tsTypes lists the contract structs in output order. Field names, optional
// markers and doc comments come from the `ts` struct tags:
//
//	ts:"name[,optional][,type=TSType][,doc=text]"   doc must come last
//	ts:"-"                                          skip the field
var tsTypes = []tsType{
	{value: ProbeContext{}, name: "ProbeContext", section: "quota_probe"},
	{value: ProbeRequest{}, name: "ProbeRequest"},
	{value: ProbeResponse{}, name: "ProbeResponse"},
	{value: ProbeStep{}, name: "ProbeStep"},
	{value: ProbeEntry{}, name: "ProbeEntry"},
	{value: ProbeResult{}, name: "ProbeResult"},
	{value: ModelListEntry{}, name: "ModelListEntry", section: "model_list"},
	{value: ModelListResult{}, name: "ModelListResult"},
	{value: CredentialCheckResult{}, name: "CredentialCheckResult", section: "credential_check", enum: &tsEnum{"CredentialStatus", CredentialStatuses}},
	{value: DetectContext{}, name: "DetectContext", section: "site_detect"},
	{value: SiteDetectResult{}, name: "SiteDetectResult"},
	{value: ProtocolEndpointContext{}, name: "ProtocolEndpointContext", section: "protocol"},
	{value: ProtocolCandidateContext{}, name: "ProtocolCandidateContext"},
	{value: ProtocolBuildContext{}, name: "ProtocolBuildContext"},
	{value: ProtocolBuiltRequest{}, name: "ProtocolBuiltRequest"},
	{value: ProtocolParseInput{}, name: "ProtocolResponse"},
	{value: ProtocolUsage{}, name: "ProtocolUsage"},
	{value: ProtocolSignInput{}, name: "ProtocolSignInput"},
	{value: ProtocolSignResult{}, name: "ProtocolSignResult"},
	{value: ProtocolErrorResult{}, name: "ProtocolErrorResult"},
	{value: ErrorClassifyContext{}, name: "ErrorClassifyContext", section: "error_classifier", enum: &tsEnum{"FailureClass", FailureClasses}},
	{value: ErrorClassifyInput{}, name: "ErrorClassifyInput"},
	{value: ErrorClassifyResult{}, name: "ErrorClassifyResult"},
	{value: ModelMetadataContext{}, name: "ModelMetadataContext", section: "model_metadata"},
	{value: ModelMetadataInput{}, name: "ModelMetadataInput"},
	{value: ModelMetadataEntry{}, name: "ModelMetadataEntry"},
	{value: ModelMetadataResult{}, name: "ModelMetadataResult"},
	{value: PricingParseContext{}, name: "PricingParseContext", section: "pricing_parse"},
	{value: PricingGroupEntry{}, name: "PricingGroupEntry"},
	{value: PricingItemEntry{}, name: "PricingItemEntry"},
	{value: PricingParseResult{}, name: "PricingParseResult"},
}

// TypeDeclarations renders the plugin SDK .d.ts: interfaces generated from the
// Go contract structs followed by the hand-written unions and host API.
func TypeDeclarations() (string, error) {
	names := map[reflect.Type]string{}
	for _, item := range tsTypes {
		names[reflect.TypeOf(item.value)] = item.name
	}
	var out strings.Builder
	fmt.Fprintf(&out, "// xLyra plugin API v1 (apiVersion %d, hostApi %d).\n", hookAPIVersion, hostAPIVersion)
	out.WriteString("// Code generated by `go generate ./cmd/xlyra-plugin`; DO NOT EDIT.\n")
	out.WriteString("// Import with `import type`; the bundle must not contain imports.\n\n")
	methods := make([]string, 0, len(probeMethods))
	for method := range probeMethods {
		methods = append(methods, fmt.Sprintf("%q", method))
	}
	sort.Strings(methods)
	for _, item := range tsTypes {
		if item.section != "" {
			fmt.Fprintf(&out, "// ---- %s ----\n\n", item.section)
		}
		if item.enum != nil {
			quoted := make([]string, len(item.enum.values))
			for i, value := range item.enum.values {
				quoted[i] = fmt.Sprintf("%q", value)
			}
			fmt.Fprintf(&out, "export type %s = %s;\n\n", item.enum.name, strings.Join(quoted, " | "))
		}
		if item.name == "ProbeRequest" {
			fmt.Fprintf(&out, "export type ProbeMethod = %s;\n\n", strings.Join(methods, " | "))
		}
		body, err := renderInterface(item, names)
		if err != nil {
			return "", err
		}
		out.WriteString(body)
		out.WriteString("\n")
	}
	out.WriteString(strings.TrimLeft(tsStatic, "\n"))
	return out.String(), nil
}

func renderInterface(item tsType, names map[reflect.Type]string) (string, error) {
	typ := reflect.TypeOf(item.value)
	var out strings.Builder
	fmt.Fprintf(&out, "export interface %s {\n", item.name)
	for i := 0; i < typ.NumField(); i++ {
		field := typ.Field(i)
		raw, ok := field.Tag.Lookup("ts")
		if !ok {
			return "", fmt.Errorf("%s.%s has no ts tag", typ.Name(), field.Name)
		}
		if raw == "-" {
			continue
		}
		name, optional, override, doc := parseTSTag(raw)
		tsType := override
		if tsType == "" {
			var ptr bool
			var err error
			if tsType, ptr, err = tsTypeOf(field.Type, names); err != nil {
				return "", fmt.Errorf("%s.%s: %w", typ.Name(), field.Name, err)
			}
			optional = optional || ptr
		}
		if doc != "" {
			fmt.Fprintf(&out, "  /** %s */\n", doc)
		}
		mark := ""
		if optional {
			mark = "?"
		}
		fmt.Fprintf(&out, "  %s%s: %s;\n", name, mark, tsType)
	}
	out.WriteString("}\n")
	return out.String(), nil
}

func parseTSTag(raw string) (name string, optional bool, typ string, doc string) {
	parts := strings.Split(raw, ",")
	name = parts[0]
	for i := 1; i < len(parts); i++ {
		part := parts[i]
		switch {
		case part == "optional":
			optional = true
		case strings.HasPrefix(part, "type="):
			typ = strings.TrimPrefix(part, "type=")
		case strings.HasPrefix(part, "doc="):
			doc = strings.TrimPrefix(strings.Join(parts[i:], ","), "doc=")
			return
		}
	}
	return
}

// tsTypeOf maps a Go type to TypeScript. ptr reports a pointer, which becomes optional.
func tsTypeOf(typ reflect.Type, names map[reflect.Type]string) (string, bool, error) {
	if typ.Kind() == reflect.Pointer {
		inner, _, err := tsTypeOf(typ.Elem(), names)
		return inner, true, err
	}
	if name, ok := names[typ]; ok {
		return name, false, nil
	}
	switch typ.Kind() {
	case reflect.String:
		return "string", false, nil
	case reflect.Bool:
		return "boolean", false, nil
	case reflect.Int, reflect.Int32, reflect.Int64, reflect.Float32, reflect.Float64:
		return "number", false, nil
	case reflect.Interface:
		return "any", false, nil
	case reflect.Slice:
		inner, _, err := tsTypeOf(typ.Elem(), names)
		return inner + "[]", false, err
	case reflect.Map:
		if typ.Key().Kind() != reflect.String {
			return "", false, fmt.Errorf("map key %s is not a string", typ.Key())
		}
		inner, _, err := tsTypeOf(typ.Elem(), names)
		return "Record<string, " + inner + ">", false, err
	}
	return "", false, fmt.Errorf("unsupported type %s", typ)
}
