// xLyra plugin API v1 (apiVersion 1, hostApi 1).
// Code generated by `go generate ./cmd/xlyra-plugin`; DO NOT EDIT.
// Import with `import type`; the bundle must not contain imports.

// ---- quota_probe ----

export interface ProbeContext {
  siteType: string;
  baseURL: string;
  credentialType: string;
  /** Unix time in milliseconds. */
  now: number;
}

export type ProbeMethod = "DELETE" | "GET" | "PATCH" | "POST" | "PUT";

export interface ProbeRequest {
  method: ProbeMethod;
  /** Path under the site base URL. Absolute URLs are rejected. */
  path: string;
  headers?: Record<string, string>;
  query?: Record<string, string>;
  body?: Json;
}

export interface ProbeResponse {
  status: number;
  headers: Record<string, string>;
  body: string;
  /** Parsed body, or null when the body is not JSON. */
  json: any;
  error?: string;
}

export interface ProbeStep {
  request: ProbeRequest;
  response: ProbeResponse;
}

export interface ProbeEntry {
  label: string;
  unit?: string;
  remaining?: number;
  limit?: number;
  used?: number;
  unlimited?: boolean;
  resetAt?: string;
  cashBalance?: number;
  voucherBalance?: number;
  grantedBalance?: number;
  toppedUpBalance?: number;
}

export interface ProbeResult {
  kind: string;
  plan?: string;
  expiresAt?: string;
  isAvailable?: boolean;
  entries: ProbeEntry[];
}

// ---- protocol ----

export interface ProtocolEndpointContext {
  downstreamPath: string;
}

export interface ProtocolCandidateContext {
  siteType: string;
  baseURL: string;
  upstreamName: string;
  upstreamModel: string;
}

export interface ProtocolBuildContext {
  candidate: ProtocolCandidateContext;
}

export interface ProtocolBuiltRequest {
  path: string;
  headers?: Record<string, string>;
  payload: Record<string, any>;
}

export interface ProtocolResponse {
  status: number;
  headers: Record<string, string>;
  body: string;
  json: any;
}

export interface ProtocolUsage {
  prompt_tokens?: number;
  completion_tokens?: number;
  total_tokens?: number;
}

export type Json = null | boolean | number | string | Json[] | { [key: string]: Json };

// ---- hook return values ----

/** Return exactly one of request, result, or error. */
export type ProbeDecision =
  | { request: ProbeRequest; result?: never; error?: never }
  | { result: ProbeResult; request?: never; error?: never }
  | { error: string; request?: never; result?: never };

export type ProtocolDecodeResult =
  | { model: string; error?: never }
  | { error: { status: number; code: string; message: string }; model?: never };

export interface ProtocolParsedResponse {
  /** Send the upstream body to the client unchanged. */
  passthrough?: boolean;
  status?: number;
  contentType?: string;
  body?: string;
  usage?: ProtocolUsage;
  error?: string;
}

// ---- host API v1 (globals) ----

declare global {
  const codec: {
    base64Encode(value: string): string;
    base64Decode(value: string): string;
    base64URLEncode(value: string): string;
    base64URLDecode(value: string): string;
  };
  const crypto: {
    hmacSHA256(key: string, message: string): string;
    sha256(message: string): string;
  };
  const jwt: {
    signHS256(payload: Record<string, any>, secret: string): string;
    decodeHS256(token: string, secret: string): any;
  };
  const utils: { uuid(): string };
  const log: {
    debug(message: string, fields?: Record<string, any>): void;
    info(message: string, fields?: Record<string, any>): void;
    warn(message: string, fields?: Record<string, any>): void;
  };
}
