// xLyra plugin API v1 (apiVersion 1, hostApi 1).
// Code generated by `go generate ./cmd/xlyra-plugin`; DO NOT EDIT.
// Import with `import type`; the bundle must not contain imports.

// ---- quota_probe ----

export interface ProbeContext {
  siteType: string;
  baseURL: string;
  credentialType: string;
  /** Unix time in milliseconds. */
  now: number;
}

export type ProbeMethod = "DELETE" | "GET" | "PATCH" | "POST" | "PUT";

export interface ProbeRequest {
  method: ProbeMethod;
  /** Path under the site base URL. Absolute URLs are rejected. */
  path: string;
  headers?: Record<string, string>;
  query?: Record<string, string>;
  body?: Json;
}

export interface ProbeResponse {
  status: number;
  headers: Record<string, string>;
  body: string;
  /** Parsed body, or null when the body is not JSON. */
  json: any;
  error?: string;
}

export interface ProbeStep {
  request: ProbeRequest;
  response: ProbeResponse;
}

export interface ProbeEntry {
  label: string;
  unit?: string;
  remaining?: number;
  limit?: number;
  used?: number;
  unlimited?: boolean;
  resetAt?: string;
  cashBalance?: number;
  voucherBalance?: number;
  grantedBalance?: number;
  toppedUpBalance?: number;
}

export interface ProbeResult {
  kind: string;
  plan?: string;
  expiresAt?: string;
  isAvailable?: boolean;
  entries: ProbeEntry[];
}

// ---- model_list ----

export interface ModelListEntry {
  /** Upstream model name, as clients must send it. */
  name: string;
  displayName?: string;
  capabilities?: JsonObject;
}

export interface ModelListResult {
  models: ModelListEntry[];
}

// ---- credential_check ----

export type CredentialStatus = "ok" | "invalid" | "unavailable";

export interface CredentialCheckResult {
  /** ok: the key works. invalid: the key is rejected. unavailable: the site could not answer, so the key is unknown. */
  status: CredentialStatus;
  message?: string;
}

// ---- site_detect ----

export interface DetectContext {
  baseURL: string;
  /** Unix time in milliseconds. */
  now: number;
}

export interface SiteDetectResult {
  matched: boolean;
  /** Required when matched: which xLyra site type this site is, such as newapi. It must be a type xLyra already supports. */
  siteType?: string;
  /** 0 to 1. */
  confidence?: number;
  features?: JsonObject;
}

// ---- protocol ----

export interface ProtocolEndpointContext {
  downstreamPath: string;
}

export interface ProtocolCandidateContext {
  siteType: string;
  baseURL: string;
  upstreamName: string;
  upstreamModel: string;
}

export interface ProtocolBuildContext {
  candidate: ProtocolCandidateContext;
}

export interface ProtocolBuiltRequest {
  path: string;
  headers?: Record<string, string>;
  payload: Record<string, any>;
}

export interface ProtocolResponse {
  status: number;
  headers: Record<string, string>;
  body: string;
  json: any;
}

export interface ProtocolUsage {
  prompt_tokens?: number;
  completion_tokens?: number;
  total_tokens?: number;
}

export interface ProtocolSignInput {
  method: string;
  /** Full upstream URL including the query string. */
  url: string;
  /** Headers about to be sent, without credentials. */
  headers: Record<string, string>;
  /** The exact request body that will be sent (at most 1 MiB). */
  body: string;
}

export interface ProtocolSignResult {
  /** The exact text to sign. At most 64 KiB. */
  stringToSign: string;
  algorithm: SignAlgorithm;
  /** Defaults to hex. */
  encoding?: SignEncoding;
  /** Header that carries the signature, such as Authorization or X-Signature. */
  header: string;
  /** Text put before the encoded signature, such as 'HMAC-SHA256 '. */
  prefix?: string;
  /** Extra non-secret headers to send, such as a timestamp or nonce. */
  headers?: Record<string, string>;
}

export interface ProtocolErrorResult {
  contentType?: string;
  /** The error body returned to the client. */
  body: string;
}

// ---- error_classifier ----

export type FailureClass = "unknown" | "limited" | "subscription_limit" | "transient" | "credential_invalid";

export interface ErrorClassifyContext {
  siteType: string;
}

export interface ErrorClassifyInput {
  status: number;
  /** Error code from the upstream body, if any. */
  code?: string;
  /** Error type from the upstream body, if any. */
  type?: string;
  /** Error message, cut to 1024 bytes. */
  message?: string;
}

export interface ErrorClassifyResult {
  class: FailureClass;
  /** Short note for logs, at most 200 bytes. */
  reason?: string;
}

// ---- model_metadata ----

export interface ModelMetadataContext {
  siteType: string;
}

export interface ModelMetadataInput {
  models: string[];
}

export interface ModelMetadataEntry {
  /** Must be one of the input model names. */
  id: string;
  /** Official display name. */
  name?: string;
  capabilities?: JsonObject;
}

export interface ModelMetadataResult {
  models: ModelMetadataEntry[];
}

// ---- pricing_parse ----

export interface PricingParseContext {
  siteType: string;
}

export interface PricingGroupEntry {
  name: string;
  displayName?: string;
  ratio?: number;
  auto?: boolean;
}

export interface PricingItemEntry {
  model: string;
  displayName?: string;
  group?: string;
  billingType?: string;
  currency?: string;
  groupRatio?: number;
  modelRatio?: number;
  completionRatio?: number;
  cacheRatio?: number;
  createCacheRatio?: number;
  createCache1hRatio?: number;
  imageRatio?: number;
  audioRatio?: number;
  audioCompletionRatio?: number;
  modelPrice?: number;
  inputValue?: number;
  outputValue?: number;
  perRequestValue?: number;
}

export interface PricingParseResult {
  groups?: PricingGroupEntry[];
  items: PricingItemEntry[];
}

export type Json = null | boolean | number | string | Json[] | { [key: string]: Json };
export type JsonObject = Record<string, Json>;

// ---- hook return values ----

/** Return exactly one of request, result, or error. */
export type ProbeDecision =
  | { request: ProbeRequest; result?: never; error?: never }
  | { result: ProbeResult; request?: never; error?: never }
  | { error: string; request?: never; result?: never };

/** Return exactly one of request, result, or error. R is the kind's result type. */
export type SteppedDecision<R> =
  | { request: ProbeRequest; result?: never; error?: never }
  | { result: R; request?: never; error?: never }
  | { error: string; request?: never; result?: never };

export type ModelListDecision = SteppedDecision<ModelListResult>;
export type CredentialCheckDecision = SteppedDecision<CredentialCheckResult>;
export type SiteDetectDecision = SteppedDecision<SiteDetectResult>;

export type ProtocolDecodeResult =
  | { model: string; error?: never }
  | { error: { status: number; code: string; message: string }; model?: never };

export type SignAlgorithm = "hmac-sha256" | "hmac-sha1" | "hmac-sha512";
export type SignEncoding = "hex" | "base64";

export interface ProtocolParsedResponse {
  /** Send the upstream body to the client unchanged. */
  passthrough?: boolean;
  status?: number;
  contentType?: string;
  body?: string;
  usage?: ProtocolUsage;
  error?: string;
}

// ---- host API v1 (globals) ----

declare global {
  const codec: {
    base64Encode(value: string): string;
    base64Decode(value: string): string;
    base64URLEncode(value: string): string;
    base64URLDecode(value: string): string;
  };
  const crypto: {
    hmacSHA256(key: string, message: string): string;
    sha256(message: string): string;
  };
  const jwt: {
    signHS256(payload: Record<string, any>, secret: string): string;
    decodeHS256(token: string, secret: string): any;
  };
  const utils: { uuid(): string };
  const log: {
    debug(message: string, fields?: Record<string, any>): void;
    info(message: string, fields?: Record<string, any>): void;
    warn(message: string, fields?: Record<string, any>): void;
  };
}
